version: '3.3'
services:
  svn:
    build: ./
    container_name: svn
    hostname: svn
    volumes: 
    - /dev/urandom:/dev/random:ro
    - ./etc/svn:/etc/svn
    - ./svn:/svn
    ports:
      - 9090:80
#    environment: 
#      MB_DB_TYPE: postgres
#      MB_DB_DBNAME: metabase
#      MB_DB_PORT: 5432
#      MB_DB_USER: /run/secrets/db_user
#      MB_DB_PASS: /run/secrets/db_password
#      MB_DB_HOST: postgres
    networks: 
      - svn
networks: 
  svn:
    driver: bridge
